# Generated by Django 3.2.4 on 2022-07-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='TaskImg',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
