# Generated by Django 3.2.4 on 2022-07-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0002_alter_addtask_taskimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='TaskImg',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
